# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cure',
            fields=[
                ('cure_id', models.AutoField(db_column='CURE_ID', primary_key=True, serialize=False)),
                ('drug_name', models.CharField(db_column='DRUG_NAME', max_length=255)),
                ('illness_name', models.CharField(db_column='ILLNESS_NAME', max_length=255)),
                ('rating', models.IntegerField(blank=True, db_column='RATING', null=True)),
                ('alcohol', models.CharField(blank=True, db_column='ALCOHOL', max_length=100, null=True)),
                ('rx_otc', models.CharField(blank=True, db_column='RX_OTC', max_length=100, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('csa', models.CharField(blank=True, db_column='CSA', max_length=100, null=True)),
                ('pregnancy', models.CharField(blank=True, max_length=100, null=True)),
                ('review_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CURE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drugdetails',
            fields=[
                ('drug_id', models.AutoField(db_column='DRUG_ID', primary_key=True, serialize=False)),
                ('drug_name', models.CharField(db_column='DRUG_NAME', max_length=255)),
                ('drug_details', models.TextField(db_column='DRUG_DETAILS')),
            ],
            options={
                'db_table': 'DRUGDETAILS',
                'managed': False,
            },
        ),
    ]
